### ISSUE TITLE
(Abandoned)

### ISSUE THREAD

**Issue by AbdulShabazz** [marytts/marytts#1100]
Why is this entire repo implemented in Java when we only need the synthesis libraries from them. For pete's sake. C++! Python! CMAKE!! This repo is unmaintainable. You should have implemented this in C, Fortran and LUA. Those are the only programming languages I can think of with more vulnerabilities....

**Comment by mgreen23** [comment]
I agree. Do you want to start a new repo with me?

**Comment by amendment19** [comment]
I agree. Do you want to start a new repo with me?

**Comment by AbdulShabazz** [comment]
No. I haven't the faintest idea how this library is supposed to operate. It is important for me start from a working model. My personal recommendation is the Whisper Speech repository which is being hosted by OpenAI for its reverse text to speech synthesis. It possess a powerful mel spectrogram generator. Or the gTTS CLI interface repo to Google Translate's text to speech API. Those models just work out of the box and more advanced parametric or tacotron models can be developed on top of them.

**Comment by psibre** [comment]
Since you bring up C++ -- incidentally, the MaryTTS architecture did briefly consider that vs. Java when it was being designed circa 2000. But Java won, as it seemed easier to support a range of hardware/OS combinations without recompiling.
Bear in mind also that while MaryTTS was intended to be a mature platform for various projects, it was always, and remains, **research** code -- not a commercial product on its own -- it's right there in the name (the *R* in MARY).

Having said that, if you want to work with a 20+ year old TTS framework that's written in C++, you could take a look at [Festival](https://www.cstr.ed.ac.uk/projects/festival/), which is mature and has quite a large community.

But if you're out for neural TTS, you're looking at the wrong project here. Try [Tacotron2](https://github.com/NVIDIA/tacotron2) or similar, and if you want a commercial, cloud-based product, obviously big tech has got you covered.

**Comment by StepanMynarik** [comment]
> Since you bring up C++ -- incidentally, the MaryTTS architecture did briefly consider that vs. Java when it was being designed circa 2000. But Java won, as it seemed easier to support a range of hardware/OS combinations without recompiling. Bear in mind also that while MaryTTS was intended to be a mature platform for various projects, it was always, and remains, **research** code -- not a commercial product on its own -- it's right there in the name (the _R_ in MARY).
> 
> Having said that, if you want to work with a 20+ year old TTS framework that's written in C++, you could take a look at [Festival](https://www.cstr.ed.ac.uk/projects/festival/), which is mature and has quite a large community.
> 
> But if you're out for neural TTS, you're looking at the wrong project here. Try [Tacotron2](https://github.com/NVIDIA/tacotron2) or similar, and if you want a commercial, cloud-based product, obviously big tech has got you covered.

Thank god for your choice. I tried so many C++ solutions before MaryTTS and just getting them to compile was a monumental task! Usually ended up with BS problems anyway since the compilation process (specific compiler, dependency versions etc.) tends to be poorly documented or not documented at all.

MaryTTS absolutely rocks! It has exactly all the bells and whistles we need.
Thank you for your work @psibre .

**Comment by psibre** [comment]
Thank you for your kind words, @StepanMynarik ! I just wish I could dedicate more time to maintaining the MaryTTS code. There are so many open todos...

**Comment by AbdulShabazz** [comment]
Working on it. And to all the descendants of Jacob in the bloodline of Christ: Brothers Isaac and Ishmael. alaikum & shalom.
