### ISSUE TITLE
Ancient sox options regression

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#168]
SoX option `-w` was deprecated in favor of `-2` in 13.0.0 (Feb 2007) and removed in 14.1.0 (July 2008); but if the version of installed, _newer_ sox cannot be determined for any reason, the HTS scripts fall back the ancient `-w`, which causes errors.

**Comment by BenjaminPoilve** [comment]
Hi, 
There seems to have been (again) a change in sox options on 14.4.2.
Replacing  -s parameters to `-e signed-integer` and SOXOPTION to `-b 16 `.
I guess for now, since it is warned that you should use sox 14.2 it is better to leave it this way, but this is just in case somebody stumble on the same issue..
