### ISSUE TITLE
rate adjustment doesn't work

### ISSUE THREAD

**Issue by nlphacker** [marytts/marytts#213]
I tried the mary client with the cmu SLT voice.

the rate audio effect has not effect at all.  there must be some bug.

**Comment by jcrumpton** [comment]
I traced the program to the processTargetList (HTSEngine.java, line 453) where calls to getDur(k) are used to compute the duration of the Gaussians. I uncommented the println calls in the method and saw the following output for Rate = 1 and input text "hello":
HTSEngine: phone=h
HTSEngine: phone=h  TagName=ph  durVal=75.0 totalDurGauss=75.0(15 frames)
   state: 0 durFromGaussians=1   durNew=1
   state: 1 durFromGaussians=1   durNew=1
   state: 2 durFromGaussians=10   durNew=10
   state: 3 durFromGaussians=2   durNew=2
   state: 4 durFromGaussians=1   durNew=1
   model=h   TotalDurFrames=15  TotalDurMilisec=75.0

For same input text and Rate = 2.8:
HTSEngine: phone=h
HTSEngine: phone=h  TagName=ph  durVal=75.0 totalDurGauss=215.0(43 frames)
   state: 0 durFromGaussians=3   durNew=1
   state: 1 durFromGaussians=3   durNew=1
   state: 2 durFromGaussians=29   durNew=10
   state: 3 durFromGaussians=3   durNew=1
   state: 4 durFromGaussians=5   durNew=2
   model=h   TotalDurFrames=15  TotalDurMilisec=75.0

The durations are being computed correctly from the Gaussians and are nearly 3 times as long as the previous output. But the values of durNew are being computed in line 453 as
      int newStateDuration = (int) (durationsFraction *  m.getDur(k) + newStateDurationFactor);

The value of durationsFraction (~0.34 in this example) is reversing the effect of calculating the longer durations so that the values of newStateDuration are the same for Rate = 1 and Rate = 2.8

I changed line 453 to be 
      int newStateDuration = (int) (m.getDur(k) + newStateDurationFactor);

Now the longer durations are used for newStateDuration and you can hear the difference in the output. For same input text and Rate = 2.8:
HTSEngine: phone=h
HTSEngine: phone=h  TagName=ph  durVal=75.0 totalDurGauss=215.0(43 frames)
   state: 0 durFromGaussians=3   durNew=3
   state: 1 durFromGaussians=3   durNew=3
   state: 2 durFromGaussians=29   durNew=29
   state: 3 durFromGaussians=3   durNew=3
   state: 4 durFromGaussians=5   durNew=5
   model=h   TotalDurFrames=43  TotalDurMilisec=215.0

I have issued a pull request with the code change.

**Comment by tady159** [comment]
I am running version 5.1.2, and rate adjustment on hmm voices doesn't have any effect.

**Comment by bittorf** [comment]
@tady159 this is definitely fixed in the 5.2-beta2 release.

**Comment by adegoodyer** [comment]
@bittorf Have downloaded the latest and can confirm this is not working.

**Comment by adegoodyer** [comment]
AM setting this particular parameter with
`marytts.setAudioEffects("Rate(durScale:2.0)");`
Other effects work except this one, happy to help if necessary

**Comment by psibre** [comment]
> Have downloaded the latest and can confirm this is not working.

@bittorf I cannot confirm your confirmation -- it works for me on v5.2 with voice-cmu-slt-hsmm. Could you please specify exactly which parameters you are passing in, and what the input MaryXML is? What is the output for different rate percentages?

**Comment by bittorf** [comment]
@psibre - sorry, cannot rollback here. i wrote for me it works at least with 5.2-beta2 - maybe even earlier (so e.g. 5.2). for now i work with master/trunk.

**Comment by Waterbyte** [comment]
I am sure the rate feature is still not working.
Steps to reproduce:
1. Open up online client of Mary TTS that is publicly available.
2. Select TEXT as input. 
3. Select AUDIO as output.
4. Audio out : WAVE FILE
5. Change durScale and apply rate effect.
6. Voice model is cmu-slt-hsmm en_US female hmm.

I am assuming that rate feature means the speed with which audio is spoken. For different durScale, there must be change is speed with which audio is spoken.

**Comment by Virus610** [comment]
I noticed this problem seems to still persist (On master) after all this time. 

Hopefully my sorta-hacky fix (#1070) is good enough. Tested locally and it seems to behave.

**Comment by StepanMynarik** [comment]
> I noticed this problem seems to still persist (On master) after all this time.
> 
> Hopefully my sorta-hacky fix (#1070) is good enough. Tested locally and it seems to behave.

Yep, doesn't work in the current release for me as well.
I hope your PR gets merged and that a new release is coming in the somewhat near future :)
Thanks for sharing with the community! This is an amazing project!
