### ISSUE TITLE
Tanscription - glottal stop is missing

### ISSUE THREAD

**Issue by LTVDev** [marytts/marytts#256]
Hello,

I'm currently working with MARY on German sentences and one issue occured regarding the transcription.
The transcriptions are mostly correct but there is one problem: glottal stop in front of vowels at the beginning of words or syllables. The problem is that it is transcribed correctly at the beginning of words starting with a vowel but missing at the beginning of syllables starting with a vowel.
For instance "am Ende" ist transcribed [?am ?End@] but "Wochenende" is transcribed without the glottal stop [vox@nEnd@] and not [vox@n?End@].

Does anybody have an idea how I could change the transciption / enter glottal stops?

Best wishes

**Comment by LTVDev** [comment]
I finally pushed my commits to my fork. Please have a look: https://github.com/LTVDev/Mary-lang-de.git

**Comment by Munzey** [comment]
the problem is that although you have edited the de transcription file, you now need to rebuild the de language resources, i.e the de_lexicon.fst and de.lts files located [here](https://github.com/marytts/marytts/tree/master/marytts-languages/marytts-lang-de/src/main/resources/marytts/language/de/lexicon). This *can* be done using the `LTSLexiconPOSBuilder` found in module `marytts-transcription` however, this relies on classes inside `marytts-builder` (specifically `LexiconCreator` in `marytts.tools.newlanguage`) and if you refer to one of the newer issues like #326 you'll notice that there are *several* problems that we are currently trying to fix with the code. Thus I would hang back on updating the resources just yet
