### ISSUE TITLE
MARY can not be trained with big corpus (12252 utterances - 20 hours)

### ISSUE THREAD

**Issue by mammadovramil** [marytts/marytts#270]
Hello everyone,

I want to train MARY with huge data (20 hrs. of utterances).
But the training fails at DurationCARTTrainer giving timeline_waveform.mry file exception "File seems corrupt: index is expected after data, not before".

```
java.lang.Exception: The component DurationCARTTrainer produced the following exception:
    at marytts.tools.voiceimport.
DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot load timeline file from /home/marytts-master/myvoice/timeline_waveforms.mry
    at marytts.unitselection.data.TimelineReader.<init>(TimelineReader.java:128)
    at marytts.unitselection.data.TimelineReader.<init>(TimelineReader.java:105)
    at marytts.tools.voiceimport.DurationCARTTrainer.compute(DurationCARTTrainer.java:136)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
Caused by: java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
    at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:745)
    at marytts.unitselection.data.TimelineReader.load(TimelineReader.java:219)
    at marytts.unitselection.data.TimelineReader.<init>(TimelineReader.java:126)
```

timeline_waveform.mry file size is 2.3GB;

And log file:

```
Opening GUI.......
Loading database layout:
Reading config file /home/marytts-master/myvoice/database.config
Reading external binaries config file /home/marytts-master/lib/external/externalBinaries.config
Loading basename list from file /home/marytts-master/myvoice/basenames.lst
Found 12252 files in basename list
Loading features from file /home/marytts-master/myvoice/mary/features.txt
---- Making a pitch synchronous waveform timeline

Processing [12252] utterances.

---- Detected a global sample rate of: [16000] Hz.
---- Folding the wav files according to the pitchmarks...
Will create the waveform timeline in file [/home/marytts-master/myvoice/mary/timeline_waveforms.mry].
00001
00002
00003
00004
00005
00006
00007
........
---- Done.
---- Waveform timeline result:
Number of files scanned: 12252
Total speech duration: [1055199702] samples / [65949.98] seconds.
(Speech duration approximated from EST Track float times: [65950.5] seconds.)
Number of frames: [11713104].
Size of the index: [659500] (10552000 bytes, i.e. 10.06 megs).
---- Waveform timeline done.
```

Anybody have solitions?

**Comment by psibre** [comment]
Not a trivial issue, since the current implementation is constrained by the maximum size of Java arrays.
@alishah-ahmed Please have a look at [TimelineTest](https://github.com/marytts/marytts/blob/c0df394604169fe520efd1d95d9b627309d9032f/marytts-builder/src/test/java/marytts/unitselection/data/TimelineTest.java) and if possible add a test that exposes this bug.

**Comment by ramil2319** [comment]
i solved this problem in c++ with jni

**Comment by psibre** [comment]
I'm glad you found a workaround! But the problem remains for our

**Comment by ramil2319** [comment]
yes, Of course. First i must test. Now i have problem in voicecompiler:

maven out>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (make-assembly) on project voice-shemsiye_unitsel_12252: Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single failed: invalid entry size -> [Help 1]
maven out>org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (make-assembly) on project voice-my_voice: Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single failed: invalid entry size
maven out>	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
maven out>	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
maven out>	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
maven out>	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
maven out>	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
maven out>	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
maven out>	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
maven out>	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
maven out>	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
maven out>	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
maven out>	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
maven out>	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
maven out>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
maven out>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
maven out>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
maven out>	at java.lang.reflect.Method.invoke(Method.java:483)
maven out>	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
maven out>	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
maven out>	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
maven out>	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
maven out>Caused by: org.apache.maven.plugin.PluginExecutionException: Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single failed: invalid entry size
maven out>	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
maven out>	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
maven out>	... 19 more
maven out>Caused by: java.lang.IllegalArgumentException: invalid entry size
maven out>	at java.util.zip.ZipEntry.setSize(ZipEntry.java:301)
maven out>	at org.codehaus.plexus.archiver.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:352)
maven out>	at org.codehaus.plexus.archiver.zip.ZipOutputStream.finish(ZipOutputStream.java:316)
maven out>	at org.codehaus.plexus.archiver.zip.ZipOutputStream.close(ZipOutputStream.java:534)
maven out>	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.close(AbstractZipArchiver.java:743)
maven out>	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:901)
maven out>	at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:512)
maven out>	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:185)
maven out>	at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:452)
maven out>	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
maven out>	... 20 more
maven out>[ERROR] 
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:344)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:94)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)

**Comment by psibre** [comment]
Have you seen [this](http://stackoverflow.com/q/19135298)?
Maybe upgrading the maven-assembly-plugin could help. Or perhaps your java version (which one are you running?)

Note that the VoiceCompiler is essentially deprecated -- we use [a gradle plugin](https://github.com/marytts/gradle-marytts-voicebuilding-plugin) for voice packaging.

**Comment by ramil2319** [comment]
i upgraded the maven-assembly-plugin and i have installed oracle java 1.8.
But this not helped.
how use gradle plugin in maryttts?

**Comment by ramil2319** [comment]
<p>Note<a href="https://github.com/marytts/gradle-marytts-voicebuilding-plugin">a gradle plugin</a> for voice packaging.</p>

**Comment by psibre** [comment]
Actually, if you just want to use your voice locally, you're already done if you create the jar file and put the resources that *would* go into the zip under your `MARY_BASE/lib/voices` (the exact paths are defined in your voice config file).

Incidentally, just how big *is* your voice data that it can't be zipped?

**Comment by ramil2319** [comment]
my voice data is 2.6 GB

**Comment by seblemaguer** [comment]
This issue is also related to this problem  #261

**Comment by Georgakopoulos** [comment]
I could create a voice with 95% of my database at 1 GB without problems, but it failed at 100% (1.1GB)!

I am a bit confused though on what to do exactly: Can somebody break it down a bit more?
How do I know which resources go into the zip, and how do I create the jar-file separately (while using the GUI)?
