### ISSUE TITLE
Rebuild English lexicon resources

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#286]
As indicated in #285, some underlying properties of CMUdict's ARPAbet transcription can bubble up in random transcriptions when the LTS rules are invoked for English. The corresponding resources should be rebuilt using the same process that has become standard practice for all other languages, and the initial step should be to preprocess the raw CMUdict into SAMPA transcription.

**Comment by seblemaguer** [comment]
We should be careful to not forget to remove the hack in AllophoneSet.syllabify

**Comment by Munzey** [comment]
not just an enhancement anymore; the major change to the syllabification process requires *all* language resources to be rebuilt.

**Comment by Munzey** [comment]
Reminder: with the new CMUdict 0.7b  we still only have a wedge entry for the letter a. This is due to a combination of problems: 
1. a lack of pos data in our new CMUdict 
2. we now build the fst and lts files for english using the seperate module marytts-transcription which as seen in #313 does not accept pos data anyway

Solution: 
1. modify cmudict with pos information somehow to allow for multiple entries for a lemma 
2. merge #313 fix and rebuild english resources

**Comment by psibre** [comment]
See also #326
