### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#293]
Hi, Unit-Selection Voicebuilding has some prerequisites:

    all speech signals are in .wav format, 16kHz sampling frequency and 16-bit sample rate.

HMM Voicebuilding also has same prerequisites? if HMM has can anybody explain why?

Can I used HTKLabeler in lieu of the EHMM Labeler during HMM Voicebuilding?

And my last question :  the used HTS version in check_install_external_programs.sh script is quite old. and when I try to use HTS new version I am getting error in different steps (example. hts_engine_API-1.09 version in lieu of 1.05).  will be changing in check_install_external_programs.sh script?  

Thanks for answers

**Comment by psibre** [comment]
> HMM Voicebuilding also has same prerequisites? if HMM has can anybody explain why?

Because of hard-coded assumptions in several places. Feel free to locate and fix those!

> Can I used HTKLabeler in lieu of the EHMM Labeler during HMM Voicebuilding?

Sure, but your mileage may vary, and the code was written with the assumption that your running it on Linux (but OSX works, too).

> And my last question : the used HTS version in check_install_external_programs.sh script is quite old. and when I try to use HTS new version I am getting error in different steps (example. hts_engine_API-1.09 version in lieu of 1.05). will be changing in check_install_external_programs.sh script?

That script is really just a hacky way to setup some paths to external programs, all of which you can (and should) install through normal means.
Having said that, if you try to use different versions of those external programs, you will most certainly encounter problems.
