### ISSUE TITLE
Problem with TrainedLTS model

### ISSUE THREAD

**Issue by timobaumann** [marytts/marytts#295]
The model that comes with CMU-SLT-HSMM for EN_US produces phoneme sequences that cannot be parsed into a syllable (missing the nucleus). 

For the word "heerd", the LTS model produces [h r d] which obviously cannot be syllabified. Synthesis fails with an exception -- maybe it would be better to back-off to using letter-to-sound rules? Or skip the failing word?

**Comment by psibre** [comment]
This is actually something we're fixing as we speak, in the `rebuild-english` branch.

**Comment by Munzey** [comment]
see #326

**Comment by psibre** [comment]
As of 9d7889f53319cdf85c8650bd93f2a9c5cbfec00a at least it doesn't throw an exception anymore. But the predicted pronunciation for "heerd" is `' d r h`, which is of course utter shite.
Holding my breath until the LTS resources are rebuilt...

**Comment by E12161** [comment]
I like to fix the bug in Problem with TrainedLTS model #295.But I
could not find where is the bug is.Can anyone help me?

**Comment by psibre** [comment]
@E12161 I think this issue will see some updates after we switch to gradle following the v5.2 release in the next few days. If you'd like to investigate the issue, part of the problem is [AllophonSet#syllabify](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-common/src/main/java/marytts/modules/phonemiser/AllophoneSet.java#L456-L629), which doesn't perform as expected, but is difficult to test properly due to the convoluted project architecture in the maven based build.
