### ISSUE TITLE
HMM Voice normalize

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#300]
Hello, 
    When I generate own HMM Voice I am getting "HMMVoiceConfigure.normalize 1" in HMMVoiceConfigure. but in final I am getting sometimes not normalize voice like in image above : 

![normalize](https://cloud.githubusercontent.com/assets/10720391/6978579/fe478274-d9ee-11e4-88cf-a1a511f162f4.png)

**Comment by NeptunSun** [comment]
When sentence start, I always hear loud voice

**Comment by sjai013** [comment]
Are you getting this issue for a female speaker?  

We had the same issue for female speakers (our sample size was 2 male speakers and 2 female speakers).  The issue is caused by the application of global variance to the higher order mel-cepstral coefficients.

We resolved it by reducing the mel-cepstral warping parameter (HMMVoiceConfigure.freqWarp) during training.  For our female speakers, we found that HMMVoiceConfigure.freqWarp=0.2 worked well, but you may have to manually fine-tune this.

**Comment by NeptunSun** [comment]
I have issue for female speaker. I am testing with  HMMVoiceConfigure.freqWarp=0.2 and will say what will be result. Thanks for answer
