### ISSUE TITLE
JPhonemiser#phonemise returns null without exception

### ISSUE THREAD

**Issue by Munzey** [marytts/marytts#314]
This allows a token to be set with attribute ph = "null" without anything breaking. This will actually synthesize audio as "null"

**Comment by psibre** [comment]
This is actually the documented behavior of [StringBuilder#append](http://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html#append%28java.lang.String%29), which apparently nobody realized back in ec57e5906dfd30d341ebb42a7b959628ab5b2b3b and c9125bf7951e57cbd6418a64c00e8e7c130988ab (when the generic and German language components were committed, respectively), since it's obviously silly to predict the pronunciation `"null"`. (Not even the *word* "null" has that pronunciation!)
