### ISSUE TITLE
Purge outdated example code

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#320]
We need to get rid of random example code, some of which is so outdated it no longer works as advertised.
Instead, we should promote (or perhaps `git subtree merge`) the [new example code repo](/marytts/marytts-txt2wav).

**Comment by blsn** [comment]
I found that the downloadable package ready folder ‘marytts-5.1.2.zip’: 
https://github.com/marytts/marytts/releases
(marytts-5.1.2\doc\examples\client)

..contains the example file ‘MaryClientUser.java’, is it outdated as well? since I’m trying (without success), to get it works (through GitHub issue # 319).

Thank you,
Mike

**Comment by psibre** [comment]
Indeed, it will only be removed in future releases... In fact, the assemblies themselves will be dropped -- there is no need for them once the new [marytts-installer](https://github.com/marytts/marytts-installer) is mainstream.
