### ISSUE TITLE
Incorrect stress in Italian lexicon source

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#328]
Further to #323, the [Italian lexicon source file](https://github.com/marytts/marytts/blob/bb2c683a4cd3ed2c4caab405801b48032e214364/marytts-languages/marytts-lang-it/lib/modules/it/lexicon/it.txt) suffers from double stress, in SAMPA _and_ ARPAbet notation (i.e., trailing `1`s on the nuclei of stressed syllables), which is redundant and can cause problems.
Those `1`s should be removed.

**Comment by psibre** [comment]
This is a another dependency of #326.

**Comment by giuliopaci** [comment]
Which problems are caused by the fact that some phone names are ending with 1? While I agree that there is some redundancy, it is just formal. Essentially the 1 in the Italian were added to encode stress and then modified to just represent vowels that exist only stressed with respect to vowels that exist only unstressed. If you want to remove the trailing 1, I think you will be safe with u, u1, a, a1, i, i1, as indeed there is a one to one mapping between stress and 1. On the other hand you have to think about a proper strategy to handle e, e1, E1, o, o1, O1.
