### ISSUE TITLE
Making the voice speak normal

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#340]
Hello, I have created new synthetic voice with using [MaryTTS]. By default (INPUT TYPE : TEXT, OUTPUT TYPE : AUDIO) making voice speak quickly.

That is why I added prosody tag as <prosody rate="-18%"> for all request if INPUT TYPE is TEXT. In SynthesisRequestHandler.java file I changed Input Type as RAWMARYXML and added prosody tags. I solve my problem this way. but I know this is not true solution. How can I fixed this problem (voice speak quickly) ? By default making voice speak normal

My second problem is when sentences size increase voice quality decrease.

Last problem is Cache. By default 
cache = false
cache.file = MARY_BASE/tmp/cache
cache.clearOnStart = false

When i change cache=true  after first sentence the voice quality decrease.

**Comment by aitorme** [comment]
@NeptunSun regarding your first problem, I am not completely sure what you mean, but there was an issue #213 with the rate adjustment, which did not allow the voice to speak faster, and this was fixed in #374. If that is what you mean, please fetch to the latest commits so your MaryTTS is updated and working properly.

**Comment by aitorme** [comment]
@NeptunSun any news regarding this issue? Is it working properly?

**Comment by NeptunSun** [comment]
Yes, it is working normal thanks.
