### ISSUE TITLE
"Maier" causes: IllegalArgumentException: Allophone `'' could not be found in AllophoneSet `sampa' (Locale: de)

### ISSUE THREAD

**Issue by alexeiarshavin** [marytts/marytts#341]
My code using the MaryTTSEmbedded example:

    MaryInterface marytts = new LocalMaryInterface();
    Set<String> voices = marytts.getAvailableVoices();
    marytts.setVoice(voices.iterator().next()); //cmu-slt-hsmm
    marytts.setOutputType("PHONEMES");
    marytts.setLocale(new Locale("de"));
    Document document = marytts.generateXML("Maier");

Note that this is the only word where it happens. So I assume it has to do with a custom phonetic encoding in the dictionary.

Other similar words work fine: Meyer Meier Mayer Mai Maiar

I have seen similar error reports, maybe that's a duplicate. 
*What is the current workaround? To which version or branch can I switch?*

**Comment by psibre** [comment]
Thanks for the report! It is indeed a duplicate, a side-effect of the re-implementation of syllabification introduced in 5.1.2, and affects syllabification of tokens that cannot be found in a lexicon. As it turns out, the solution is somewhat more complicated, requiring the complete rebuilding of letter-to-sound resources across all languages.

Workarounds for now are either
* fall back to 5.1.1, or
* if it only affects a small number of words in a limited domain, you could try adding them to the `userdict`.

Sorry for the inconvenience; this is at the top of the todo list for the upcoming 5.2.
