### ISSUE TITLE
URL of the generated wav files..

### ISSUE THREAD

**Issue by blsn** [marytts/marytts#410]
I have a simple client-server web application with MaryTTS:

```java
MaryInterface marytts = new RemoteMaryInterface("localhost", 59125);
AudioInputStream AIS = marytts.generateAudio(sayit);
```

I would like to use in my app the HTML ```<audio>``` element to embed the speech content in documents.
For that I need to supply a URL in the ```‘src’``` attribute as below:
```html
<audio controls>
  <source src="path/to/audiofile.wav" type="audio/wav">
</audio>
```
I understand that some methods in the above ```‘AudioInputStream’``` object, include obtaining an audio input stream from an external audio file, stream, or URL.   
  
Is MaryTTS HTTP server generates somewhere a URL for the raw wav file?

**Comment by psibre** [comment]
The HTTP server does not save files anywhere, so there is no raw wav file to link to. Having said that, the HTTP request *itself* can be treated as a URL to a wav file, because that's exactly what it returns.

I think there might be confusion about the two different ways to get audio from MaryTTS. You're using the MaryInterface, which gets you an AudioInputStream, but you're doing so remotely, on a separate instance of MaryTTS running as a HTTP server.
But if you need to get your audio as a URL to a wav file, why not simply construct an HTTP request and send that to [http://localhost:59125](http://localhost:59125) in en exactly the same way as you would in your web browser? That gives you the wav content directly (RIFF header and everything).

**Comment by blsn** [comment]
Thank you for your help, you're totally right.
 
I found the following HTTP server front end to MaryTTS:
https://github.com/draffensperger/marytts-http

Probably I will check the above in the solution that you offered to me.

**Comment by psibre** [comment]
@blsn thanks for the [link](/draffensperger/marytts-http)!
@seblemaguer have a look sometime if it's useful to our html5 gui?
