### ISSUE TITLE
XTSE0280: Element name *|text() is not a valid QName

### ISSUE THREAD

**Issue by mrvisser** [marytts/marytts#455]
I'm having a really strange issue. The `SableParser` is having trouble parsing the XSLT file when it's run in the context of IntelliJ, but it seems to work fine if I run it through sbt using `sbt run`. The program I'm running is pretty simple (Scala):

```scala
object MaryMain {

  def main(args: Array[String]): Unit = {
    println(System.getProperty("java.version"))
    val lmi = new LocalMaryInterface
    write(lmi.generateAudio("this is great, if only it will work in both intellij and SBT :("), "out.aiff")
  }

  private def write(ais: AudioInputStream, file: String) = {
    AudioSystem.write(ais, AudioFileFormat.Type.AIFF, new File(file))
  }
}
```

And the output is:

```
1.8.0_65
Error at xsl:strip-space on line 36 column 41 
  XTSE0280: Element name *|text() is not a valid QName
Exception in thread "main" marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at MaryMain$.main(MaryMain.scala:13)
	at MaryMain.main(MaryMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.Exception: Problem starting module SableParser
	at marytts.server.Mary.startModules(Mary.java:151)
	at marytts.server.Mary.startup(Mary.java:297)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 7 more
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)
	at marytts.modules.SableParser.startup(SableParser.java:69)
	at marytts.server.Mary.startModules(Mary.java:149)
	... 11 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:371)
	at marytts.server.Mary$2.run(Mary.java:290)
```

I'm using Scala but that shouldn't effect the Mary runtime at all.

Java 1.8.0_65 (both intellij and sbt runtime)
Running on 5.2-SNAPSHOT (checked out today)

The deps I'm using are:

```
  "de.dfki.mary" % "marytts-common" % "5.2-SNAPSHOT",
  "de.dfki.mary" % "marytts-runtime" % "5.2-SNAPSHOT",
  "de.dfki.mary" % "voice-cmu-slt-hsmm" % "5.2-SNAPSHOT"
```

Any idea?

**Comment by seblemaguer** [comment]
Hello,

I do not manage to reproduce that using my java configuration. Which voice are you using ?

**Comment by dehydrator** [comment]
I had the same problem. The root cause is that TransformerFactory picked up the net.sf.saxon implementation used in other parts of the program, which thinks the sable_to_mary.xslt has invalid format. To solve it, you either 1) force TransformerFactory use the default implementation when calling java command line: -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl, or 2) suppress service interface in your maven pom.xml : <exclude>META-INF/services/javax.xml.transform.TransformerFactory</exclude>

Reference: https://docs.oracle.com/javase/7/docs/api/javax/xml/transform/TransformerFactory.html

Use the javax.xml.transform.TransformerFactory system property.
Use the properties file "lib/jaxp.properties" in the JRE directory. This configuration file is in standard java.util.Properties format and contains the fully qualified name of the implementation class with the key being the system property defined above. The jaxp.properties file is read only once by the JAXP implementation and it's values are then cached for future use. If the file does not exist when the first attempt is made to read from it, no further attempts are made to check for its existence. It is not possible to change the value of any property in jaxp.properties after it has been read for the first time.
Use the Services API (as detailed in the JAR specification), if available, to determine the classname. The Services API will look for a classname in the file META-INF/services/javax.xml.transform.TransformerFactory in jars available to the runtime.
Platform default TransformerFactory instance.

**Comment by akprats33** [comment]
Hi @dehydrator . I am facing the same issue. I tried to force the implementation of `TransformerFacotry`. I didn't help at all. I used the following snipped :- 

```
System.setProperty("javax.xml.transform.TransformerFactory", "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
```

I tried `Saxon xslt processor` but that didn't help either. Please let me know if there is anything else I could do to fix this.

**Comment by dehydrator** [comment]
@akprats33 Your can always read the source code to tell what the system is trying to do: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/javax/xml/transform/TransformerFactory.java
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/javax/xml/transform/FactoryFinder.java

I would first try if setting the command line argument is going to work:
"java -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl 'your classpath' 'your main class'"

I didn't use command line, instead, I have one line to exclude saxon service in my package, knowing that the other part of my program does not really use this implementation. 
`                <configuration>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                                
                                <exclude>META-INF/services/javax.xml.transform.TransformerFactory</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>`

**Comment by ataraxis** [comment]
@akprats33 Did you ever get this working? I'm running into the same issue. If I force the TransformerFactory this problem goes away, but then I'm back to the issue I had that brought me here: https://github.com/marytts/marytts/issues/740

**Comment by akprats33** [comment]
@ataraxis Yes. I tried to re-connect to `mary interface`. It fails for the first time but somehow works on the second attempt. Changing `Transformerfactory` didn't help. It works using `play framework`. I haven't tried it in pure `scala` though.

**Comment by ataraxis** [comment]
@akprats33 Thanks for the response. I tried creating a stripped-down Play 2.6 application (2.6 no longer has a dependency on Xerces). That got rid of the Xerces warnings mentioned in the other bug, but didn't fix the parsing error.

I eventually got it to work by including a version Xalan from Apache on the classpath. Not sure why that one works but the version included with Java doesn't, but it works even on older versions of Play (and on the first attempt).
