### ISSUE TITLE
Support for Number Expansion in Russian language

### ISSUE THREAD

**Issue by Rootex** [marytts/marytts#497]
The Russian voice `vocforg-ru-nsh male unitselection general` does not process numbers of any kind, this is because the `Number Expansion` have not yet been implemented for this language.
##### Example

`InputType:` TEXT
`Input:` 6547

`OutType:` WORDS
`Output:`

```
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="ru">
<p>
<s>
<t>
6547
</t>
</s>
</p>
</maryxml>

```

**Notice** The number supposed to be expanded to the word tokens of the given language.

**Comment by Rootex** [comment]
@Munzey You know this particular module, give me some tips on how to approach this, if there is a new structure of implementing this features please elaborate it so i don't assume based on pre-existing implementations.

Both the ``italian`` and ``german`` language followed the same implementation as what i integrated into the ``russian``, but i seem to be mistaken on the procedure, so i will await your reply before i proceed.

**Comment by Munzey** [comment]
so german is obviously one of the original languages implemented around what, 2001 2002? Java as a language has come pretty far since then so there's probably a lot of room for optimization. I don't think the ExpansionPattern model is bad per say, however if I recall correctly the reason I scrapped trying to do it that way for luxembourgish initially was that there seemed to be no benefits to it. If we use the [german Preprocess class](https://github.com/marytts/marytts/blob/master/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/Preprocess.java) as a start point, we see that Preprocess#expandSayasElements is going to do nothing for a language unless its had these SAYAS elements added which  I assume happens somewhere in the Jtokenizer module(which is actually just a wrapper for dfki Jtok package, another beast entirely).

 Lets assume for languages like russian or luxembourgish its not going to add these. Then we get to the really fun bit of trying to decipher what exactly is happening in ExpansionPattern#process which is called in Preprocess#matchAndExpandPatterns. So it starts to try find the optimal ep and we get to the fact that each of these sub expansion patterns are then essentially embedded into this overall Preprocess structure, making it really difficult to just, for example, simplify some methods in NumberExpansion class by using an icu formatter instead. Its just not worth the hassle. Couple this with the fact that one needs to use the excruciating w3c dom package to do anything, and simplifying the whole process down starts to make more sense(albeit at the cost of speed). So yes you could keep the old way of doing things as you did in your pull request, but im not so sure it's in the spirit of moving forward. That's just my 2 cents. maybe a better starting point would be to have a look at how one could optimize the english preprocess module instead? anyone have any thoughts on this? One can see from comparing lb to en preprocess module, while its all fine when youre only accounting for one type of expansion(numbers and dates) but once you want to start adding more stuff a bunch of if else statements doesn't really cut it.

**Comment by Rootex** [comment]
Ok i get you point, thanks alot i will look into this and see what i can come up with.

**Comment by Rootex** [comment]
#534

**Comment by Rootex** [comment]
#534
