### ISSUE TITLE
PraatPitchmarker Failure: basenames.lst not recognized?!

### ISSUE THREAD

**Issue by aWelker** [marytts/marytts#540]
Hi,

this morning I downloaded the latest version of marytts, successfully performed a mvn install and started the voiceimport.sh with my voicebuilding directory. Now, when trying to run the very first component, namely the PraatPitchmarker, the following things happen:

1) terminal: 
```Found 13302 files in basename list
Computing pitchmarks for 13302 utterances.
Running Praat as: praat /home/.../Mary/voice-dfki-antje/temp/script.praat /home/.../Mary/voice-dfki-antje/basenames.lst /home/.../Mary/voice-dfki-antje/wav/ /home/.../Mary/voice-dfki-antje/pm/ 100 500```
2) the two typical praat windows pop up
3) script.praat from /temp/script.praat pops up
4) another window pops up, giving the following warning:
```
File “/home/.../Mary/voice-dfki-antje/basenames.lst” not recognized.
Script line 1 not performed or completed:
« Read from file... /home/.../Mary/voice-dfki-antje/basenames.lst »
Script not completed.
```

How is this even possible, and does anyone know how to fix it? I tried multiple times, also started voiceimport.sh in a plain new voicebuilding directory so it had to create a new list - failure.

Thanks in advance for any help and ideas!

**Comment by aWelker** [comment]
Just for the record, I get the same error when using a newly downloaded and compiled mary version 5.1.1 and an empty voicebuilding directory containing only a wav and text directory with two objects each. Updating praat doesn't have any effect either.

**Comment by nshmyrev** [comment]
Does the output really have three dots `/home/.../Mary/voice-dfki-antje/basenames.lst`  instead of username here or your replaced it manually? It seems like something is just misconfigured an the path was wrong.

For pitchmarks it is better to use Google Reaper between, it must be much more accurate.

**Comment by aWelker** [comment]
Hi, no, the path is right in the original output - it must be, as the praat script resides in voice-dfki-antje/temp/ and the file is referenced by ../basenames.lst in the script

**Comment by nshmyrev** [comment]
Provide your database.config file please

**Comment by aWelker** [comment]
Okay, here you go
[database .config.txt](https://github.com/marytts/marytts/files/300498/database.config.txt)

**Comment by aWelker** [comment]
Okay, so I kind of solved the problem by running the praat component on my rather slow laptop, zipping the created directory and transferring that to the pc, it seems that the other components do not have any problems.
I tried out some creative locations for mary and the voice directory, but always got the same exception - my best guess is that there might be a bug when using Ubuntu 16.04 (?)

**Comment by psibre** [comment]
For the record, this issue is caused by an incompatibility between Praat 5 and 6.

From [the manual](https://web.archive.org/web/20150923102326/http://www.fon.hum.uva.nl/praat/manual/Scripting_6_9__Calling_from_the_command_line.html) for Praat 5:
> ## Command lines on Unix and Macintosh
> 
> On Unix or MacOS X, you call Praat scripts from the command line like this:
> ```
> > /people/mietta/praat doit.praat 50 hallo
> ```
> or
> ```
> > /Applications/Praat.app/Contents/MacOS/Praat doit.praat 50 hallo
> ```
> This opens Praat, runs the script **doit.praat** with arguments "50" and "hallo", and closes Praat.

From [the manual](http://www.fon.hum.uva.nl/praat/manual/Scripting_6_9__Calling_from_the_command_line.html) for Praat 6:
> ## 4. Calling Praat to run a script
> 
> Now we are ready to discuss how to run Praat without a GUI.
> 
> [...]
> 
> On the Mac, you type
> ```
> /Applications/Praat.app/Contents/MacOS/Praat --run "my script.praat"
> ```
> and on Linux
> ```
> /usr/bin/praat data/hello.wav --run "my script.praat"
> ```
> What happens on all platforms is that the Console or Terminal starts up Praat, then Praat executes the script, and then Praat closes itself.

and

> ## 7. What happens if I specify neither --open nor --run?
> 
> If you specify neither `--open` nor `--run`, Praat's behaviour is not guaranteed. If you type something like
> ```
> praat testCommandLineCalls.praat "I love you" 0.4 "Me too"
> ```
> into a Console or Terminal window by hand, Praat will typically run the script. Also, the `--run` option can probably be left out from the Python call above. However, if you redirect the output of Praat to a file or pipe, you cannot typically leave out the `--run` option; if you do, Praat may start its GUI and *open* the file rather than run it.

With the legacy **VoiceImportTools**, if you have Praat 6 installed, you must ensure that `praat` is called with the `--run` option. An easy way to do this is to append ` --run` to the `PraatPitchmarker.command` configuration in `database.main` (or by editing the settings in the DatabaseImportMain GUI).

The [Gradle MaryTTS Voicebuilding Plugin](/marytts/gradle-marytts-voicebuilding-plugin/) has heuristics to detect which version of Praat is installed, and run the command with the correct syntax.

**Comment by psibre** [comment]
@aWelker I assume this has been solved?

**Comment by haquynh1505** [comment]
@psibre : I'm getting the same problem while trying to import a new voice. 
I've been following the procedure written here https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial
And the voice I've used to import was downloaded from here http://www.speech.cs.cmu.edu/cmu_arctic/packed/cmu_us_slt_arctic-0.95-release.tar.bz2
Unfortunately, I've got the same problem with PraatPitchmaker. There are some windows popped up with the following warnings 
File “/voice/data/demo/basenames.lst” not recognized.
Script line 1 not performed or completed:
« Read from file... /voice/data/demo/basenames.lst »
Script not completed.
----------------------------------------------------------------
File “/voice/data/demo/wav/” contains no audio data.
Script line 1 not performed or completed:
« Read from file... /voice/data/demo/wav/ »
Script not completed.
-----------------------------------------------------------------
File “/voice/data/demo/pm/” contains no audio data.
Script line 1 not performed or completed:
« Read from file... /voice/data/demo/pm/ »
Script not completed.
------------------------------------------------------------------
Cannot open file “/voice/sources/marytts-5.x/target/marytts-builder-5.3-SNAPSHOT/bin/100”.
Script line 1 not performed or completed:
« Read from file... 100 »
Script not completed.
-------------------------------------------------------------------
Cannot open file “/voice/sources/marytts-5.x/target/marytts-builder-5.3-SNAPSHOT/bin/500”.
Script line 1 not performed or completed:
« Read from file... 500 »
Script not completed.
-------------------------------------------------------------------

I don't understand as I do have wav files data in the wav directory. 
And I've tried your solution, adding appending --run to the PraatPitchmarker.command 
Could you tell me what is the problem here? Thanks in advance!

**Comment by psibre** [comment]
@haquynh1505 What is the output of `which praat` and `praat --version`? Also, please **attach** your `database.config`.

**Comment by haquynh1505** [comment]
The output of which praat: /voice/soft/praat//praat
The output of praat --version: Praat 6.0.21 (September 25 2016)
And this is the database.config 


[database.config.tar.gz](https://github.com/marytts/marytts/files/557997/database.config.tar.gz)

**Comment by psibre** [comment]
In your `database.config`, the command is still the one that is incompatible with Praat 6:
```
# Properties for module PraatPitchmarker:
PraatPitchmarker.command praat
```
Please quit the VoiceImportTools GUI, edit the `database.config` by appending the `--run` argument, then retry.

**Comment by haquynh1505** [comment]
@psibre : it works! it's my bad not quitting the GUI while modifying the database.config. Thank you so much! :)

**Comment by MomnaSaeed** [comment]
@psibre should the command in Database.config be like this ?


i added --run , and
![image](https://cloud.githubusercontent.com/assets/9119099/25651577/447a583c-2ffd-11e7-9d32-fd953270302f.png)

 run the voice import tools , this exception came 
![image](https://cloud.githubusercontent.com/assets/9119099/25651551/23c26490-2ffd-11e7-8127-9384a037bda3.png)

**Comment by psibre** [comment]
Obviously you made a mistake. It should be `praat --run`, not `--run praat`.

**Comment by MomnaSaeed** [comment]
@psibre 
Thank you so much for correcting the command it sorted the errors but the issue of no audio after building is still there please help me in it
