### ISSUE TITLE
Redstart show Transcription

### ISSUE THREAD

**Issue by BaimAT** [marytts/marytts#580]
Hi everyone. I have a few questions.

1) In Redstart there is an option to show Transcription. where does Redstart get the transcription from and what is the format? Example, is it "text|t e x t".
2) Does this transcription will be used in HMMvoicecreation step?

I have this concern because in my allophone file, I have several digraph(?). So if it is for example 'ng' its allophone is 'N', 'kh' is 'x' and few others. During Transcription step, the train and predict wrongly. It always separates the digraph even though I transcribed a few manually before train and predict. Example 'mengaum|m @ n - g aU m' instead of 'mengaum|m @ - N aU m'.

So, is there a workaround to control this and to ensure the HMMvoicecreation steps were done correctly? Thanks

**Comment by psibre** [comment]
> 1) In Redstart there is an option to show Transcription. where does Redstart get the transcription from and what is the format? Example, is it "text|t e x t".

Honestly, I don't know, because I've never used Redstart. It was developed before I joined, and there hasn't been any work on it since. So I can't tell you how it works any better than what you can read in the documentation.

>  2) Does this transcription will be used in HMMvoicecreation step?

I don't think so, because those are totally different steps. Although the transcription should of course match.

> I have this concern because in my allophone file, I have several digraph(?). So if it is for example 'ng' its allophone is 'N', 'kh' is 'x' and few others. During Transcription step, the train and predict wrongly. It always separates the digraph even though I transcribed a few manually before train and predict. Example 'mengaum|m @ n - g aU m' instead of 'mengaum|m @ - N aU m'.

The transcription step is again separate from the two steps mentioned above. Moreover, there are some issues there as well...

**Comment by BaimAT** [comment]
@psibre Thanks for the reply. During HMMVoiceCreation steps, several folders and files were created. I go through some and notice an allophone folder. Is it advisable for me to edit any wrong allophones (if any) before executing the next steps, given that I know which step produce the folder and files?

**Comment by psibre** [comment]
> I gone through some and notice an allophone folder. Is it advisable for me to edit any wrong allophones (if any) before executing the next steps, given that I know which step produce the folder and files?

No, unless you want to risk wasting your time. Those files are generated automatically, so any edits you make would be unceremoniously overwritten and lost if you then run certain voicebuilding components again. The notable exceptions are the raw input directories `text`, `wav`, and `rawmaryxml`. The third of these is arguably the answer to your question, since it allows you to provide manually corrected MaryXML files to use as input, [which will be preferred by the AllophonesExtractor](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-builder/src/main/java/marytts/tools/voiceimport/AllophonesExtractor.java#L182-L187).

**Comment by BaimAT** [comment]
@psibre  ok got it. that aside, how to install my created voice manually? what does step 6 in [here](https://github.com/marytts/marytts/wiki/Publishing-a-MARY-TTS-Voice) means?

**Comment by psibre** [comment]
You should disregard the instructions on the ["Publishing..." wiki page](../wiki/Publishing-a-MARY-TTS-Voice) -- it has not been updated in years and doesn't reflect our current practices...
At the end of the voicebuilding process, you get a zip file and an XML component descriptor, ready for distribution. Those can be copied into any MaryTTS installation's `download` directory, and then "installed" using the `marytts-component-installer` script.

If you want to share your voicebuilding *project* (with or without these distribution files, which you could upload to GitHub as release assets), please take a look at any of our recently updated voice repositories, such as [voice-dfki-spike](/marytts/voice-dfki-spike).

**Comment by BaimAT** [comment]
I tried using `marytts-component-installer` but the new voice didn't show. So, i tried unzipping to `lib` like you mentioned [here](https://github.com/marytts/marytts/issues/569)

**Comment by psibre** [comment]
Glad it worked for you! Feel free to open new issues if you have any. =)
