### ISSUE TITLE
Utterance structure and dataset creation for training a new voice model

### ISSUE THREAD

**Issue by kosmasK** [marytts/marytts#628]
Dear MarryTTS community,

Currently I am trying to build a dataset for a new voice. While preparing my data I noticed that the already existing mary voice datasets have utterances which generally range from 2 sec to 5 sec. So, I treated this as a rule and took care so that my utterances' durations are time-limited accordingly. Also I think that it requires to have silences smaller than 200ms in each utterance.

However, I was wondering if it plays role the structure of the utterance in order to achieve the correct intonation. For example, should my utterances end with a full stop? Can they include commas? Should they be grammatically correct with a meaning, or they can be just a sequence of simple words?

I know that the audio WAVs need to be aligned with the text and the phonemes but I am not sure what are the exact rules of the utterances in order to meet the requirements of a proper training process. I would appreciate some enlightenment and guidance on those issues!

Peace!

**Comment by nshmyrev** [comment]
Hi @kosmasK 

Overall you need to understand that system simply learns what is already in the training database. If question intonation not in the training database, it will never learn to reproduce it. If there are no short pauses on commas, voice will never render them properly. So you definitely need utterances with commas in database.

Sentence should definitely be grammatically correct, otherwise voice talent will not be able to speak
them in a natural manner, you will always have unneeded brakes and stops.

There could be voices of different purpose, for example some people build voices for voice reading, those never need very strong intonation, you just render the text without emotions. Such voices are easier to build because they are more flat, but also they are limited in capabilities.

If you want something more natural and emotional like voice for virtual assistant, you need much more intonation and sentence patterns in a database, and such voices are harder to build because you will have to put more effort to properly annotate such database.

Overall, modern voices require large variety of intonations and structures and you can use large amounts of data as well. For that reason I personally recommend not to record your own prompts but instead to take an audiobook large enough and simply segment it on sentences. This way you will get much more voice data to train the system with much higher variety of acoustic signal. There are books for many major languages on http://librivox.org website, you can use them for voice construction. That will save you a lot of time and allow to create high-quality voice. Just make sure that the book is prose, not some poem.

**Comment by kosmasK** [comment]
Dear @nshmyrev 
I apologize for my delay in replying to you, but I was trying to create a new voice as described at the wikis. For this reason I will create a new issue. However I will place some questions with respect to your answer in this issue.

> "If question intonation not in the training database, it will never learn to reproduce it"

Does this mean that allophones can be modeled differently according to how they are placed in relation to question marks, commas, full stops, etc? For instance, in the following examples:

"Time to eat, kids. " and  "Time to eat kids!" 

Is the word kids (and corresponding phonemes) modeled differently, according to the difference in punctuation context? In other words: does it matter if punctuation is explicitly present in the text, or is it sufficient that the speaker’s voice is “represented” with different types of intonation? To give another example, say that I have an audio of my speaker asking the time, does it make any difference if the corresponding transcription is:

"What time is it?" or "What time is it,"  if my audio stays the same?

So you suggest me to include breakpoints in the txt file of each utterance?

> “If you want something more natural and emotional like voice for virtual assistant, you need much more intonation and sentence patterns in a database, and such voices are harder to build because you will have to put more effort to properly annotate such database.”

I am interested into building a voice like this. But why is more difficult to annotate the dataset? Isn’t it the same procedure? Utterances need to be represented in wav and  text, isn't that correct?

> “Mary wiki recommends to build prompts from wikipedia. This solves license problem, but not intonation problem, your voice will likely be flat.”

Are you referring to the process of building a new language? The english language of Mary doesn’t support intonations?

> "You can not train a good voice with 1 hour of data. For that reason I personally recommend not to record your own prompts but instead to take an audiobook large enough (20-30 hours of data) and simply segment it on sentences."

So the english US and British HMM voices of Mary are builded with 20-30 hours of data?? Even those with no intonation? And finally what are the required steps in order to retrieve an english speakin voice with intonation?

And a couple more questions: in the course of building my own voice, I followed standard procedure in that I put together a collection of relatively short spoken utterances along with their transcriptions. Why is it that I cannot “feed” the system with some books and their audiobooks in their entirety, without having to cut them down to utterances? I can imagine that, since I haven’t seen it anywhere mentioned as a possibility, there must be an important reason to avoid doing it, still, given that it would be a lot more convenient, I’d like to know the underlying reason. In the same vein, is there a standard as to how long my utterances need be? I’ve noticed in the cmu_us_slt_arctic_hts dataset that most audio excerpts are between 2 and 5 seconds long but, would it be a problem if I included shorter or longer audio samples? Generally speaking, what are the details and structure of a proper utterance and so on a correct dataset?

I really appreciate your support! Thank you in advance!
Best

**Comment by nshmyrev** [comment]
> Is the word kids (and corresponding phonemes) modeled differently, according to the difference in punctuation context? In other words: does it matter if punctuation is explicitly present in the text, or is it sufficient that the speaker’s voice is “represented” with different types of intonation?

Yes, of course just like human does. Punctuation is included in features for prediction of audio parameters.

> But why is more difficult to annotate the dataset? Isn’t it the same procedure? Utterances need to be represented in wav and text, isn't that correct?

Emotional databases might be manually annotated for intonation events.

 > The english language of Mary doesn’t support intonations?

I didn't said that.

> So the english US and British HMM voices of Mary are builded with 20-30 hours of data?? Even those with no intonation? 

I didn't said that either. You can download arctic slt database from which the main voice was built.

> And finally what are the required steps in order to retrieve an english speakin voice with intonation?

You can read textbook on that http://svr-www.eng.cam.ac.uk/~pat40/ttsbook_draft_2.pdf

> Why is it that I cannot “feed” the system with some books and their audiobooks in their entirety, without having to cut them down to utterances? 

Algorithms do not support long utterances. They can't align long audio to text reliably, so they need short audio.

>  In the same vein, is there a standard as to how long my utterances need be? 

Less than 20 seconds.

> I’ve noticed in the cmu_us_slt_arctic_hts dataset that most audio excerpts are between 2 and 5 seconds long but, would it be a problem if I included shorter or longer audio samples? 

Yes.

> Generally speaking, what are the details and structure of a proper utterance and so on a correct dataset?

See the textbook above.
