### ISSUE TITLE
Target directory (almost) empty after mvn install

### ISSUE THREAD

**Issue by Sjord** [marytts/marytts#633]
I have cloned the repository and ran `mvn install`. It says the build succeeded, but I have only this in my target directory:

    target/failsafe-reports/failsafe-summary.xml

And not `marytts-server` as expected. A search for `marytts-server` gives these two locations:

    ./build/marytts-6.0-SNAPSHOT/bin/marytts-server
    ./marytts-assembly/assembly-runtime/src/runtime/bin/marytts-server

But both fail with the error

    Error: Could not find or load main class marytts.server.Mary

Some more info:

    # mvn --version
    Warning: JAVA_HOME environment variable is not set.
    Apache Maven 3.3.9
    Maven home: /usr/share/maven
    Java version: 1.8.0_91, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
    Default locale: en_US, platform encoding: ANSI_X3.4-1968
    OS name: "linux", version: "3.16.0-4-amd64", arch: "amd64", family: "unix"

**Comment by psibre** [comment]
> `Warning: JAVA_HOME environment variable is not set.`

Looks like Maven cannot find your Java compiler (`javac`) and is not doing anything, but for some reason fails to abort.

> `Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre`

...possibly because it's only finding a JRE.

Please ensure you have a full JDK installed, and that your `JAVA_HOME` is set to it correctly.

**Comment by psibre** [comment]
Oh wait, just realized that I misread the detail that you're building `6.0-SNAPSHOT` from the `master` branch...

If you really want to build `6.0-SNAPSHOT`, please run `./gradlew build` instead of `mvn install`. But note that this will not give you the MaryTTS application.
On the other hand, to get the application and documented behavior, *check out the `5.x` branch* and then run `mvn install`.

**Comment by Sjord** [comment]
Thanks @psibre, building the 5.x branch worked.
