### ISSUE TITLE
Transcription issue New Language Support

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#645]
Hi,

I have a question regarding step 4 in New Language Support.
It says:

Copy runtime files from the transcription tool:

marytts-lang-xy/src/main/resources/marytts/language/xy/lexicon/allophones.xy.xml
marytts-lang-xy/src/main/resources/marytts/language/xy/lexicon/xy.lts
marytts-lang-xy/src/main/resources/marytts/language/xy/lexicon/xy_lexicon.fst
marytts-lang-xy/src/main/resources/marytts/language/xy/tagger/xy_pos.fst

But, after successfully transcribing the entire sample "most frequent wordList" in my database with the transcription.sh, i get only the following 2 files created.
as.lts
as_lexicon.fst

So I am in short of  as_pos.fst file and as_pos.list files.

Can I proceed without these files?

Please help.

Regards,
Jayanta

**Comment by psibre** [comment]
Did you provide part-of-speech annotations in your lexicon?

**Comment by jayanta1122** [comment]
Hi psibre,
I am a new user of MaryTTs. I've been trying to run New Language Support for my own language Assamese.I followed the instruction from https://github.com/marytts/marytts/wiki/New-Language-Support. I successfully transcript most frequent words using transcription tool ,however i find  as_pos.fst file is not created.

I attach here the  allophone.as.xml and as.txt files

[as.txt](https://github.com/marytts/marytts/files/608448/as.txt)
[allophones.as.xml.tar.gz](https://github.com/marytts/marytts/files/608451/allophones.as.xml.tar.gz)

**Comment by psibre** [comment]
Looks like your `as.txt` file contains only tokens and transcriptions, but no POS tags. Therefore, there is no data to train the `as_pos.fst` file, which I suppose is why it's not created.

I know nothing about Assamese, but if you have parts of speech, and they could be used for homograph disambiguation or as features for prosody prediction, then perhaps adding the missing POS tags and retraining would make sense at this stage.

Otherwise, you should be able to proceed, but be aware that you might have to tweak things a little downstream to avoid errors when `pos` attributes are missing or something like that.

**Comment by jayanta1122** [comment]
@psibre Thank you so much for your help.I add POS tags and now its working.

**Comment by neouyghur** [comment]
@jayanta1122  how did you add pos tags, could you offer an example? thanks.
