### ISSUE TITLE
problem in MaryTTS Installer

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#769]
I successfully compile the voice and now I want to publish my voice and i am following https://github.com/marytts/marytts/wiki/Publishing-a-MARY-TTS-Voice. But my language is not shown in MaryTTS Installer.please help

**Comment by psibre** [comment]
The legacy InstallerGUI was designed to show the languages only if corresponding XML descriptors are found in the correct location. You need to prepare an XML file that matches the format of the others (`MARYBASE/installed/marytts-lang-*-component.xml`) in order to display your language -- and any installable voices for it -- in that GUI.

Alternatively, please note that you do not need to "install" your voice using the GUI. What's required to load and use your voice is merely to place the required jar files under `MARYBASE/lib` -- and for unit-selection voices, ensure that the data files are unpacked under `MARYBASE/lib/voices`.
