### ISSUE TITLE
MaryTTS on ARM

### ISSUE THREAD

**Issue by OriginalsByToto** [marytts/marytts#777]
Hello,
I'm using the MaryTTS client (the JAR to be included in the class path of eclipse to phonetise text).
On my computers, Windows and Ubuntu, it's works perfectly, my program starts in 4-5 seconds but I just bought a Raspberry PI 3 Model B, with 1GB of RAM and Raspbian, but when I launch my program, it takes about 10-15 minutes to be ready.

On Google, I found that this problem cames from the ARM architecture.

Can I load modules in different threads at the same time?

Thank you in advance

**Comment by psibre** [comment]
You're comparing apples to, um, raspberries. All of the specs of the Pi are far below what your desktops are likely to have, never mind the architecture. Also, it sounds like you're running your software via Eclipse, which is arguably a performance hog. Have you tried profiling? Because it's not clear at all from what you report that your problem is really only due to MaryTTS.

**Comment by Wil31** [comment]
Hello, 
I am really interested in finding out if someone has achieved running MaryTTS on a Raspberry pi 4, with good performance and results.
Also, can I install it the same way as for Linux? 
My goal is to integrate this in my Python program beside voice recognition.
Should I create a new Issue for this topic ?
