### ISSUE TITLE
java.version 9 is < 3 characters

### ISSUE THREAD

**Issue by tinspin** [marytts/marytts#783]

**Comment by seblemaguer** [comment]
Hello,

could you develop as I don't get it. Thanks

**Comment by tinspin** [comment]
https://github.com/marytts/marytts/blob/master/marytts-runtime/src/main/java/marytts/server/EnvironmentChecks.java#L46

**Comment by seblemaguer** [comment]
ok thanks got it :)

**Comment by seblemaguer** [comment]
Java 9 is apparently not released. I will wait to see how the version is encoded.

**Comment by psibre** [comment]
A few notes on this:
1. That block of (sloppy) code was written over 10 years ago and hasn't been touched since. Thanks for pointing it out, @tinspin 
1. We should be checking for Java 7 or later
1. Instead of string handling, we should be using something slightly more high-level, such as `SystemUtils.JAVA_VERSION_FLOAT` from Commons-Lang or similar.
1. The required Java runtime version is already managed using the build system (maven-enforcer-plugin in MaryTTS v5.x, and Gradle for MaryTTS 6.x), and baked into the jar, so really there is no need for this in the EnvironmentChecks class at all.
1. The whole EnvironmentChecks class is scheduled for removal -- we just haven't merged it into the master branch yet.

**Comment by seblemaguer** [comment]
the logic for the environment is completely different from version 6.x and it solved  by gradle

**Comment by psibre** [comment]
Ubuntu artful (17.10) has openjdk-9-jdk, and I've verified that it breaks various things. In fact I don't even get to this error because of java.security issues.
But I'll reopen this, because eventually, we'll want to solve it as discussed above.

**Comment by weikengchen** [comment]
Yes. I am in favor of the idea to remove the environment check. @psibre  Theoretically speaking, people generally have a higher version of Java.

**Comment by wborn** [comment]
Are there any plans to create a 5.2.x release with this fix @psibre ?
Perhaps you also have a rough ETA for the 6.0 release that does contain this fix.

It would nice if we could use MaryTTS in openHAB with the forthcoming Java 11 release without having to patch/fork MaryTTS ourselves. :wink:

**Comment by psibre** [comment]
@wborn We've been busy with other components and plugins, but we're just in the process of coming back to the core marytts repo. The plan is to merge master into 5.x, and 6.x into master, and release 6.0-beta and 5.3 more or less back to back. I can't make any promises, but it should happen in the coming weeks.
Meanwhile, master [builds fine with Java 8 through 10](https://travis-ci.org/psibre/marytts/builds/430520862).

**Comment by wborn** [comment]
Thanks for the update @psibre ! :+1: I'll then use the current master for some testing in the meantime.
