### ISSUE TITLE
how to use plain text instead of wiki for creating a language resource

### ISSUE THREAD

**Issue by neouyghur** [marytts/marytts#791]
Hi, I am trying to add a new language. The language does not have plenty wiki source, therefore I am trying to use plain text files instead of wiki. 

How can I do that? 

A solution I come up is that turn the plain text file to the wiki format.

**Comment by psibre** [comment]
We actually did this a few months ago for [Polish](../../marytts-lang-pl). We created a [Polish lexicon](../../marytts-lexicon-pl) which uses a [Gradle plugin](../../gradle-marytts-lexicon-compiler-plugin) to process and "compile" a plain-text [lexicon file](../../marytts-lexicon-pl/blob/master/modules/pl/lexicon/pl.txt).
Once various issues (e.g., text encoding, allophone label mapping) had been fixed, it took only moments to run MaryTTS with Polish support.
You could take a look at those repositories and try it for your language.

**Comment by neouyghur** [comment]
Thanks for replying. Since I  don't know the Gradle, I didn't totally understand your explanation. Could you explain it more detailly?

**Comment by eximius313** [comment]
@psibre Great work!
Why don't you submit this as officially supported language?

**Comment by psibre** [comment]
@eximius313 You can use the Polish components and voices -- they are already "official" in the sense that they are repositories owned by the [marytts team](https://github.com/marytts). But there are many rough edges, such as missing text normalization.
In the near future, the Polish voices may become official in the sense that they can be installed by the updated [marytts-installer](https://github.com/marytts/marytts-installer).
Note that we plan to externalize the various language components from the main marytts repository, instead of adding new ones; all language components should have their own dedicated repositories.
