### ISSUE TITLE
Can I do someting to make it support Chinese? 

### ISSUE THREAD

**Issue by iamcaochong** [marytts/marytts#796]

**Comment by psibre** [comment]
This was done for Blizzard Challenge 2009 -- see [this paper](http://festvox.org/blizzard/bc2009/dfki_Blizzard2009.pdf). However, the code and data were never released publicly, due to IP issues. Moreover, we never had any Chinese developers working on MaryTTS, so it's no surprise that the word error rate was so high.

At this time, unless you're confident you know how to develop MaryTTS components and have open-source Chinese NLP resources available, I would recommend you look elsewhere; various commercial TTS systems such as those from iFlyTek or Alibaba are *much* better than what could be realized with MaryTTS without some dedicated development. For research systems, you should also have a look at work done at USTC.

**Comment by iamcaochong** [comment]
@psibre Thanks for reporting.
