### ISSUE TITLE
restricted allophone

### ISSUE THREAD

**Issue by guliashvili** [marytts/marytts#813]
In Georgian there are some kind of phonemes which has specific Rationalizing is different form Ind-European phonemes, in this case what suggest can be given ?
 for  example q̇ (ყ) which is characterized mostly for Caucasian languages

**Comment by fuzeller** [comment]
Do you mean because it is a "uvular stop"? (1). I have not tried to add a new "cplace" (like "uvular"), but you could possibly try using the nearest articulation placement available in MaryTTS, which is "velar" (v), so it wou look something like this in the allophones list:

	<consonant ph="ყ" ctype="s" cplace="v" cvox="-"/>

That may conflict with the real velar stops in Georgian, but I thin it's worth a try.

(1) https://en.wikipedia.org/wiki/Georgian_language

**Comment by guliashvili** [comment]
Thanks @fuzeller

**Comment by psibre** [comment]
@guliashvili for the record, you want the **phonetic symbol** (in whichever notation you choose) to be the attribute in your XML, *not* the **grapheme**.
