### ISSUE TITLE
How would I find technical talent to either help me create a new language or voice?

### ISSUE THREAD

**Issue by kalani96746** [marytts/marytts#876]
Aloha,

I'm search for development help (paid) in creating a TTS for the Hawaiian Language, either voice (en_US) or a seperate language (haw).

I've taken a look at the sources as well as the VoiceBuilder; but haven't yet been able to get anything working.  Are there developers/freelancers available (paid) who could assist with the creation of the Hawaiian Language (ʻŌlelo Hawaiʻi) or as a voice?

Hawaiian has 13 letters, aeiouhklmnpw and ʻ (ʻokina), the vowels sound similar to spanish and we have a macron called the kahakō which goes above vowels (āēīōū) and lengthens the sound.  There is also some vowel blending (think kaeo) which can occur between words too (think ka eo).

Is anyone able to look at this and help.  I am considering all sorts of help from basic guidance, to voice building assistance (voice data/text would be provided), to the creation of a totally new tts language.   (I am a software engineer not very familiar with nlp/tts).  However i am able to likely offer good compensation (through my employer) who is interested in developing this language in tts technology for non-profit release to the public.

If someone available to provide assistance or you are able to please let me know.

Mahalo nui,

Kalani Bright

**Comment by kalani96746** [comment]
Closing this as I found the mailing list but please let me know if interested

**Comment by psibre** [comment]
Since MaryTTS language and voice modules use data and models trained from data, the first question is, do you have Hawaiian data?
Given the relatively straightforward relationship of text and pronunciation for Hawaiian, it is probably more feasible to try grapheme-to-phoneme conversion with rules than, say, for French. But our "language-building" workflows are designed to be generic, given a pronunciation dictionary.

Once that is ready, we can use it to align features with a set of speech recordings (~30-60 min. should do) and use that to build a Hawaiian TTS voice.

**Comment by fuzeller** [comment]
Hi @kalani96746 - I'm a linguist with TTS voice building experience. If you're still looking for help with your project, I'd be interested!
