### ISSUE TITLE
online demo unavailable?

### ISSUE THREAD

**Issue by rootli** [marytts/marytts#881]
Hi! Is the online demo unavailable? http://mary.dfki.de:59125/ 

The demo page loads with default values (Bienvenue and Pierre). If I don't change any settings and click SPEAK, an audio player UI appears (play button, "0:00", and progress bar), but it's grayed out. When I click "Save audio file", the browser tries to open http://mary.dfki.de:59125/process with many arguments,  but never downloads anything. After a long while it says ERR_CONNECTION_RESET.

This happens on Opera/Chrome/IE/Firefox on Windows 7. If I change file settings: Firefox says "Cannot use audio tag for audio/..." for any *_FILE setting. The other browsers say they can use neither AIFF_FILE nor AU_FILE; they display no message when I select WAVE_FILE. Still none of them downloads or plays any demo.

(I didn't try other voices than the default.) 

Also, on http://mary.dfki.de/download/index.html, the link to http://mary.dfki.de/download/5.2/marytts-installer-5.2.zip says 404 Not Found. I can download the runtime marytts-5.2, and github also works, so it's not a blocker. Just mentioning it.

Thanks!

**Comment by rootli** [comment]
PS: https://github.com/marytts/marytts/wiki links to http://mary.opendfki.de/trac/wiki/ProsodySpecificationSupport which is also 404.

**Comment by psibre** [comment]
The online demo is back. Usually it's just blocked by random people abusing it as a webservice, and it restarts automatically.

The various broken links under mary.dfki.de/download are due to a recent overhaul of how we generated the webpage. Setting up the redirects to missing assets is on our todo list for this week.

The old TRAC at mary.opendfki.de works fine for me. Incidentally, we are planning to migrate the documentation on the wiki to the new website when we have time.

**Comment by rootli** [comment]
Thanks! :)
