### ISSUE TITLE
can't build 5.3 snapshot with maven 3.6 and openjdk 12 (12.0.2)

### ISSUE THREAD

**Issue by rkizito** [marytts/marytts#926]
I'm having trouble building marytts 5.3 (5.x) with maven 3.6 and openjdk 12.  i'm getting the following error when i run "mvn clean install".

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compil
er-plugin:3.8.1:compile (default-compile) on project marytts-common
: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to 
execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile 
(default-compile) on project marytts-common: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExe
cutor.java:215)

**Comment by psibre** [comment]
Indeed, the 5.x branch has not received the maintenance required to make it work with Java versions "after eight". If you want to build the 5.x branch with Maven, you need to use Java 8.
Otherwise, please build the master branch with Gradle; this should work much better than the Maven build with Java versions up to and including 12. The resulting build artifacts should be more or less equivalent (if not better).
Note that the current release plan is to merge master into 5.x and drop support for Maven builds in v5.3.0.

**Comment by rkizito** [comment]
Thanks @psibre . I had to make many changes to the 'main' pom.xml file. I got past this by updating some plugins, but so far i'm stuck at the marytts-assembly/assembly-builder. An issue with "could not find artifacts ... jar-with-dependencies". Trying to figure out which plugin version needs changing. 

But i agree with you, gradle is really the way to go.
