### ISSUE TITLE
Illegal Reflective Access Warning

### ISSUE THREAD

**Issue by vindicatorr** [marytts/marytts#949]
```
Feb 12 06:45:21 computerName systemd[1135]: Started MARY TTS.
Feb 12 06:45:25 computerName marytts-server[1147]: openjdk version "11.0.6" 2020-01-14
Feb 12 06:45:25 computerName marytts-server[1147]: OpenJDK Runtime Environment (build 11.0.6+10)
Feb 12 06:45:25 computerName marytts-server[1147]: OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)
Feb 12 06:45:33 computerName marytts-server[1147]: MARY server 5.2 starting as a HTTP server...WARNING: An illegal reflective access operation has occurred
Feb 12 06:45:33 computerName marytts-server[1147]: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/opt/marytts/lib/marytts-client-5.2-jar-with-dependencies.jar) to method java.lang.Object.finalize()
Feb 12 06:45:33 computerName marytts-server[1147]: WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
Feb 12 06:45:33 computerName marytts-server[1147]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Feb 12 06:45:33 computerName marytts-server[1147]: WARNING: All illegal access operations will be denied in a future release
Feb 12 06:45:54 computerName marytts-server[1147]:  started in 28.152 s on port 59125
```

**Comment by fquirin** [comment]
I wonder if it is necessary at all to include Groovy. [A quick search](https://github.com/marytts/marytts/search?p=1&q=groovy&unscoped_q=groovy) shows that it is basically only used for Luxembourgish language and some build tools and tests, mostly for XML stuff. Since it is 8MB overhead (of a 50MB total build) it would be great to move this from the core package to where its actually needed. When you include MaryTTS via Maven and exclude the Groovy dependency completely the server will still run without any issues.

**Comment by psibre** [comment]
Yes, we should not leak the `groovy-all` dependency. This was a source of issues for years, because it would consistently clash with the Groovy on the buildscript classpath for newer Gradle versions.

This is already done, and will be a big improvement for the imminent next release.

**Comment by psibre** [comment]
FWIW, here's a relevant upstream issue: gradle/gradle#3118
