### ISSUE TITLE
How to force the synthesis to use longer connected diphone string

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#983]
Hi guys,

maybe it has already been asked, if so please point me to the correct thread.

I got a German voice where I got several occurrences of the same words recorded and built into. But still when synthesising those words they're build from many different recordings. Even though I got the right diphone string recorded like that several times.

I know the context in the sentence is taken into consideration.

I got as far as understanding that
- the beamsize
- the values in `halfphoneUnitFeatureDefinition_ac.txt`

influence which recordings are considered for the synthesis.

So how can I force using longer strings of the originally recorded material?

Cheers!

**Comment by seblemaguer** [comment]
Hello,

I am a little bit confused with your question: 
   - I guess you are using a unit selection voice right? 
   - assuming you have multiple occurrences of the full word. Is your question is "why the system is not using one instance of the full word (i.e using units from different word)?" or "why can't I select a specific instance of the word among the available ones?"

**Comment by entenbein** [comment]
Hi, 

thanks for the quick reply!

- Yes, I'm using a unit selection voice.
- My actual question is the first one you suggested: _Even though there are several occurrences of just the right diphones in the right order, a word consisting of those diphones gets build from different (non connected) recordings. How to avoid that?_

**Comment by psibre** [comment]
It's crucial to recall that the unit selection cost has two components, the *target* cost and the *join* cost, with corresponding weight coefficients. You're asking how to modify the unit selection process such that the join cost has a higher weight, relative to the target cost.

Fortunately, the original authors of MaryTTS implemented exactly what you need in the form of the `voice.<NAME>.viterbi.wTargetCosts` property, which is by default set to 0.7. It's used in [UnitSelectionVoice](https://github.com/marytts/marytts/blob/b4c8a1c09f761bdb8bd4dfadfc55158a2ceb9f32/marytts-runtime/src/main/java/marytts/unitselection/UnitSelectionVoice.java#L182) and applied (as `targetCostWeight`) to the UnitSelector when it loads the UnitDatabase. There it's then used in the [`selectUnits` method](https://github.com/marytts/marytts/blob/b4c8a1c09f761bdb8bd4dfadfc55158a2ceb9f32/marytts-runtime/src/main/java/marytts/unitselection/select/UnitSelector.java#L110) where it constructs a Viterbi instance (as `wTargetCosts` again), which finally uses this to balance the join cost and target cost:
[`wJoinCosts = 1 - wTargetCosts`](https://github.com/marytts/marytts/blob/92821b688d86ad8aa7d2d109a2d1a4dd6b9d9fd2/marytts-runtime/src/main/java/marytts/unitselection/select/viterbi/Viterbi.java#L123)

And then, finally, we reach the heart of the unit selection algorithm, where the [total cost is calculated](https://github.com/marytts/marytts/blob/92821b688d86ad8aa7d2d109a2d1a4dd6b9d9fd2/marytts-runtime/src/main/java/marytts/unitselection/select/viterbi/Viterbi.java#L487-L493) for each Viterbi path.

The point of course is that if you want the join cost to be more prominent when it's balanced against the target cost, so that units belonging together (no join cost) are more likely to be selected in sequence *even if their target cost is high*, then you can simply tune the value of that one voice property and see if that works for you.

The bad news is that -- unless you're debugging and changing the variable on the fly -- you'll need to restart MaryTTS to reload the voice with the new value each time you modify it.

The good news however is that you don't need to repackage the voice with a modified config resource each time -- you could simply do something like this:
```
JAVA_OPTS=-Dvoice.cmu-slt.viterbi.wTargetCosts=0.9 bin/marytts-server
```

**Comment by entenbein** [comment]
Alright, that clarifies things!

Thanks a lot!
